### PR TITLE
Merging latest changes from develop into master

### PR DESCRIPTION
**Pull request by ernestkamara**
Would be nice if you can merge this so that i can test and verify #32

### CODE REVIEW

**Comment by arimorty** [comment]
It is merged into [https://github.com/arimorty/floatingsearchview/tree/develop](url). In general, I like to merge pull requests into the develop branch and then merge into master. I hope that helped.

**Comment by jakubkrolewski** [comment]
@arimorty Could you, please, merge develop to master and release a new version with the recent fixes?

**Comment by arimorty** [comment]
@ernestkamara I haven't been contributing to the library for a couple of months, but I recently started working on some improvements based on your and other contributers' suggestions, as well as a new addition that you will see in the next release. The next release will also contain this pull request and will be available to use with gradle. The release is probably going to come within the next two weeks.

As a side note, I would be thrilled to hear from you and others what project you are using this library for. Perhaps a screenshot of the screen would be nice to see. :)

In any case, thanks for contributing,
Ari

**Comment by ernestkamara** [comment]
Sounds great! Our app is currently in beta release, but would send you the link to the Play Store when we are fully released. I suggest you add some more reviewer(assignees), since it can speed up contribution.

**Pull request closed without merging**
