### PR TITLE
Fixing restoring search suggestions

### PR DESCRIPTION
**Pull request by jakubkrolewski**
Fix for  #32

### CODE REVIEW

**Comment by jakubkrolewski** [comment]
@arimorty So, is the fix OK for you?

**Comment by arimorty** [comment]
Hi @jakubkrolewski,

Can you branch out from 'develop' and do a new pull request with your changes? In this library we merge new features into 'develop' rather than 'master'.

Thanks for contributing.

**Comment by jakubkrolewski** [comment]
I've created new PR #41

**Comment by arimorty** [comment]
Great, your changes were merged into develop and will be part of the next release.

Thanks again for contributing.

**Pull request closed without merging**
